### ISSUE TITLE
Wrong dataset?

### ISSUE THREAD

**Issue by GuillaumeLam** [GMvandeVen/continual-learning#15]
https://github.com/GMvandeVen/continual-learning/blob/d281967802396b146b2c30b6667369c6f2395472/train.py#L123

Hello! My team and I are currently running experiments with your BI-R repo. We are trying to find the limit between ER and GR approaches and see how much we can degrade examplars (stored or generate) to acheive similar accuracies. As such, we ported your implementation of ER to the other repo. We noticed that on the line 123 of train.py, that the dataset train_datasets is used rather than previous_datasets. Is train_datasets not the full scale dataset? We would love to have your input on this potential issue and if you have and ablation/directions of experiments to run, please do tell! 
Btw, your code is absolutely beautiful and so well documented!

**Comment by GMvandeVen** [comment]
Hi, thank you for your feedback! You’re right, there was indeed a mistake in the line that you point out, it should have used `previous_datasets` rather than `train_datasets`. This mistake caused wrong behaviour in the setting `--replay=exemplars` (i.e., replay from a limited-size memory buffer) in the Task-IL scenario. Sorry about that! I hope it didn't cause too much trouble. I just fixed it. Many thanks for letting me know!

**Comment by GuillaumeLam** [comment]
Thank you for answering so quickly! We picked up the issue when integrating the code so no harm done!
