### ISSUE TITLE
average EWC pickle

### ISSUE THREAD

**Issue by Johswald** [GMvandeVen/continual-learning#6]
hey again, it seems that you save incorrect accuracies (averages) in the pickle. In the first list of "all_tasks" should be the accuracies tested when all tasks are trained correct? I did not check other methods but for online EWC they seem wrong whereas when training on SI it seems correct. Can you check that? Thanks!

**Comment by GMvandeVen** [comment]
Hey, I quickly checked but I couldn't find any mistakes and those accuracies saved into the pickle seem correct to me. I think the confusion is with how the "all_tasks" entry is organised, which isn't very intuitive. The first list of "all_tasks" actually contains the test accuracy for the first task measured after training on each of the tasks. The _n_-th entry of the _m_-th list is the test accuracy for task _m_ after training on task _n_. Sorry for that weird structure. I hope this explains it, but if not please let me know and I'll have another look.

**Comment by Johswald** [comment]
Hey, thank you. I will check that again. Many benchmarks show the accuracy of task 1-n after training all on all tasks. To get that I have to iterate over the lists in „all_tasks“ and then get the last entry? Thank you again

**Comment by GMvandeVen** [comment]
Yes, that's correct!

**Comment by Johswald** [comment]
Ok, because I was confused about the results. When I run online EWC for 100 tasks 
(./main.py --ewc --online --lambda=5000 --gamma=1 --experiment permMNIST --scenario task --tasks 100 --fc-units=1000 --lr=0.0001)

When I extract the accuracy now as you said for all tasks after learning all tasks, the accuracies for more recent tasks are low.
Assuming I extracted the acc’s correctly, then new tasks are not able to get high accuracies. It looks like this

[0.9565, 0.9502, 0.9283, 0.9196, 0.8324, 0.898, 0.8769, …,  0.7797, 0.7696, 0.7805]

The last entry here is the acc of task n, directly after learning it. That would mean the regularisation hinders the network to actually learn new tasks (?), and protects the 
network well from forgetting the old tasks (really well). Did you experience the same? Do you suggest other hyper parameters?
Many thanks!

**Comment by GMvandeVen** [comment]
Yes, that looks about right to me. The regularisation of EWC indeed hinders the network to learn new tasks (because it penalizes new parameter changes), and this effect gets larger the more tasks have been learned. You can make the network more plastic by reducing lambda (or reducing gamma might also work), which will probably increase the accuracies for the later tasks but reduce those for the earlier tasks. What the optimal values of these EWC hyper parameters are heavily depends on both the type and number of tasks. (The optimal values for different task protocols can differ by several orders of magnitude, see for example Appendix D here: https://arxiv.org/abs/1904.07734.)

**Comment by Johswald** [comment]
Thank you again!
