### ISSUE TITLE
How to apply iCaRL on task and domain scenario?

### ISSUE THREAD

**Issue by WangTianduo** [GMvandeVen/continual-learning#8]
There is always an error when I want to apply iCaRL in the scenario of task and domain

**Comment by GMvandeVen** [comment]
This error is because iCaRL is only compatible with training according to the Class-IL scenario. The reason for this is that iCaRL uses distillation of current task data on the classes of all previous tasks using binary classification loss (in my code this is indicated by the flag `--bce-distill`, which is automatically selected when the flag `--icarl` is used), and this aspect of iCaRL does not have a straight-forward translation to the Task- or Domain-IL scenarios.
Two other aspects of iCaRL could however also be used for training according to the other scenarios: (1) the use of stored exemplars for classification (indicated by the flag `--use-exemplars`) and (2) the replay of stored exemplars during training (which can be selected with the option `--replay=exemplars`). In Appendix C of our latest preprint (https://arxiv.org/abs/1904.07734) we explore the use of these two aspects of iCaRL in the different scenarios. I should note that a third aspect of iCaRL that could be used in all scenarios is the use of binary (instead of multi-class) classification loss (indicated by the flag `--bce`).
Finally, another option could be to use iCaRL to train according to the Class-IL scenario, and then evaluate the performance according to the Task- or Domain-IL scenario. It could however be argued that this is not very fair on iCaRL as its performance won't be optimised for the scenario it is tested on. For this last option you would have to slightly modify the code.
Hope this helps!

**Comment by WangTianduo** [comment]
Thanks a lot!
It is much clearer more me now.
